baseURL = 'https://www.fsv-unterjesingen.de/'
languageCode = 'de-de'
title = 'FSV Unterjesingen'
timeout = '1h'

[params]
clubName = 'Flugsportverein Unterjesingen e.V.'
tagline = 'Segelflug, Motorsegler und Gemeinschaft am Schönbuchrand'
ctaText = 'Mitfliegen & Mitglied werden'
ctaLink = '/kontakt/'
openaipApiKey = 'bf2df3ae9c5c969fe269d1418df194f2'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = 'Fliegen lernen'
    identifier = 'fliegen-lernen'
    weight = 1
  [[menu.main]]
    name = 'Segelflugausbildung'
    pageRef = '/segelflug/fliegen-lernen'
    parent = 'fliegen-lernen'
    weight = 1
  [[menu.main]]
    name = 'Motorsegler-Ausbildung'
    pageRef = '/motorflug/motorsegler'
    parent = 'fliegen-lernen'
    weight = 2
  [[menu.main]]
    name = 'Motorflugausbildung'
    url = 'https://www.motorflugschule.info'
    parent = 'fliegen-lernen'
    weight = 3

  [[menu.main]]
    name = 'Segelflug'
    identifier = 'segelflug'
    weight = 3
  [[menu.main]]
    name = 'Allgemeines'
    pageRef = '/segelflug/allgemeines'
    parent = 'segelflug'
    weight = 1
  [[menu.main]]
    name = 'Streckenflug'
    pageRef = '/segelflug/streckenflug'
    parent = 'segelflug'
    weight = 2
  [[menu.main]]
    name = 'Alpensegelflug'
    pageRef = '/segelflug/alpensegelflug'
    parent = 'segelflug'
    weight = 3

  [[menu.main]]
    name = 'Motorflug'
    identifier = 'motorflug'
    weight = 4
  [[menu.main]]
    name = 'Echo Klasse'
    pageRef = '/motorflug/echo-klasse'
    parent = 'motorflug'
    weight = 1
  [[menu.main]]
    name = 'Motorsegler'
    pageRef = '/motorflug/motorsegler'
    parent = 'motorflug'
    weight = 2
  [[menu.main]]
    name = 'Ultraleicht (UL)'
    pageRef = '/motorflug/ultraleicht'
    parent = 'motorflug'
    weight = 3

  [[menu.main]]
    name = 'Verein'
    pageRef = '/verein'
    identifier = 'verein'
    weight = 5
  [[menu.main]]
    name = 'Über uns'
    pageRef = '/verein/ueber-uns'
    parent = 'verein'
    weight = 1
  [[menu.main]]
    name = 'Flugzeugpark'
    pageRef = '/verein/flugzeugpark'
    parent = 'verein'
    weight = 2
  [[menu.main]]
    name = 'Flugplatz Poltringen'
    pageRef = '/verein/flugplatz'
    parent = 'verein'
    weight = 3
  [[menu.main]]
    name = 'Webcam Flugplatz Poltringen'
    pageRef = '/verein/webcam'
    parent = 'verein'
    weight = 4
  [[menu.main]]
    name = 'Vereinsheim Unterjesingen'
    pageRef = '/verein/vereinsheim'
    parent = 'verein'
    weight = 5
  [[menu.main]]
    name = 'Chronik'
    pageRef = '/verein/chronik'
    parent = 'verein'
    weight = 6

  [[menu.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 6

  [[menu.main]]
    name = 'Kontakt'
    pageRef = '/kontakt'
    weight = 7
