baseURL = 'https://www.fsv-unterjesingen.de/'
languageCode = 'de-de'
title = 'FSV Unterjesingen'
timeout = '180s'

[params]
clubName = 'Flugsportverein Unterjesingen e.V.'
tagline = 'Segelflug, Motorsegler und Gemeinschaft am Schönbuchrand'
ctaText = 'Mitfliegen & Mitglied werden'
ctaLink = '/kontakt/'
openaipApiKey = 'bf2df3ae9c5c969fe269d1418df194f2'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = 'Start'
    pageRef = '/'
    weight = 1
  [[menu.main]]
    name = 'Segelflug'
    url = '#'
    identifier = 'segelflug'
    weight = 2
  [[menu.main]]
    name = 'Allgemeines'
    pageRef = '/segelflug/allgemeines'
    parent = 'segelflug'
    weight = 1
  [[menu.main]]
    name = 'Fliegen lernen'
    pageRef = '/segelflug/fliegen-lernen'
    parent = 'segelflug'
    weight = 2
  [[menu.main]]
    name = 'Streckenflug'
    pageRef = '/segelflug/streckenflug'
    parent = 'segelflug'
    weight = 3
  [[menu.main]]
    name = 'Alpensegelflug'
    pageRef = '/segelflug/alpensegelflug'
    parent = 'segelflug'
    weight = 4
  [[menu.main]]
    name = 'Verein'
    pageRef = '/verein'
    identifier = 'verein'
    weight = 4
  [[menu.main]]
    name = 'Über uns'
    pageRef = '/verein/ueber-uns'
    parent = 'verein'
    weight = 1
  [[menu.main]]
    name = 'Flugplatz Poltringen'
    pageRef = '/verein/flugplatz'
    parent = 'verein'
    weight = 2
  [[menu.main]]
    name = 'Flugzeugpark'
    pageRef = '/verein/flugzeugpark'
    parent = 'verein'
    weight = 3
  [[menu.main]]
    name = 'Vereinsheim Unterjesingen'
    pageRef = '/verein/vereinsheim-unterjesingen'
    parent = 'verein'
    weight = 4
  [[menu.main]]
    name = 'Webcam'
    pageRef = '/verein/webcam'
    parent = 'verein'
    weight = 5
  [[menu.main]]
    name = 'Chronik'
    pageRef = '/verein/chronik'
    parent = 'verein'
    weight = 6
  [[menu.main]]
    name = 'Kontakt'
    pageRef = '/kontakt'
    weight = 7
  [[menu.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 5
  [[menu.main]]
    name = 'Bilderarchiv'
    pageRef = '/bilder'
    parent = 'verein'
    weight = 7
